from __future__ import annotations

TRADING_DAYS_YEAR = 252
CHART_YEARS_DEFAULT = 1
CHART_DEFAULT_LIMIT = TRADING_DAYS_YEAR * CHART_YEARS_DEFAULT + 30
CHART_MAX_LIMIT = 6000
FUND_CHART_DEFAULT_LIMIT = CHART_DEFAULT_LIMIT
